### ISSUE TITLE
[meta] Provide alternative(s) to missing seal functions in the solang-contracts

### ISSUE THREAD

**Issue by realnimish** [Laguna-Chain/laguna-chain#70]
## Info

**description:**
Solang currently doesn't support all the seal APIs exposed by the pallet-contract. Provide alternative approaches to make them available in solidity contracts and note the ones whose alternative is not available.

**expected results:**
- Create system-contract which would expose the missing APIs to solang-based contracts
- Document the availability of the said APIs and how to use them.

**missing seal APIs:**
- [ ] seal_call_chain_extension
- [x] seal_is_contract
- [ ] seal_caller_is_origin
- [ ] seal_set_code_hash
- [x] seal_code_hash
- [x] seal_own_code_hash
- [ ] seal_delegate_call
- [x] seal_ecdsa_recover
- [x] seal_ecdsa_to_eth_address
- [ ] seal_contains_storage
